/**
 * Copyright (c) 2006-2024, JGraph Holdings Ltd
 * Copyright (c) 2006-2024, draw.io AG
 */
// null'ing of global vars need to be after init.js
window.VSS_CONVERT_URL = null;
window.EMF_CONVERT_URL = null;
window.ICONSEARCH_PATH = null;
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
window.ICONSEARCH_PATH = null;
EditorUi.enableLogging = false; //Disable logging
window.EMF_CONVERT_URL = null;
EditorUi.enablePlantUml = true; //Enables PlantUML
App.prototype.isDriveDomain = function() { return true; }
